# ----- TUMBLR: 認証 -----
TUMBLR_CONSUMER_KEY = ENV["TUMBLR_CONSUMER_KEY"]
TUMBLR_CONSUMER_SECRET = ENV["TUMBLR_CONSUMER_SECRET"]
TUMBLR_OAUTH_TOKEN = ENV["TUMBLR_OAUTH_TOKEN"]
TUMBLR_OAUTH_TOKEN_SECRET = ENV["TUMBLR_OAUTH_TOKEN_SECRET"]
TUMBLR_URL = ENV["TUMBLR_URL"]

# ----- SLACK: 認証 -----
SLACK_TOKEN = ENV["SLACK_TOKEN"]
SLACK_CHANNEL = ENV["SLACK_CHANNEL"]
SLACK_BOT_ACCOUNT = ENV["SLACK_BOT_ACCOUNT"]
SLACK_USER_ID = ENV["SLACK_USER_ID"]